- name: Get {{ etcd_service_name }} service status
  ansible.builtin.systemd_service:
    name: "{{ etcd_service_name }}"
  register: service_status

- name: Stop {{ etcd_service_name }} service
  ansible.builtin.systemd_service:
    name: "{{ etcd_service_name }}"
    state: "stopped"
  when: service_status.status.ActiveState == "active"
