# Member update
- block:
  - name: Set etcdctl command
    ansible.builtin.set_fact:
      etcd_etcdctl: "{{ etcd_home ~ '/etcdctl --endpoints ' ~ inventory_hostname ~ ':' ~ etcd_client_port ~ ' --cacert ' ~ etcd_truststore_file ~ ' --cert ' ~ etcd_cert_file ~ ' --key ' ~ etcd_key_file }}"

  - name: Get member list
    ansible.builtin.shell:
      cmd: "{{ etcd_etcdctl ~ ' member list' }}"
    register: member_list

  - name: Update peer urls
    ansible.builtin.shell:
      cmd: "{{ item }}"
    with_items: "{{ member_list.stdout_lines | map('regex_replace', '([^,]+), [^,]+, ([^,]+),.*', etcd_etcdctl ~ ' member update \\1 --peer-urls=http://\\2:' ~ etcd_peer_port) }}"

  when: inventory_hostname == groups[etcd_group_name][0]
  
- name: Set config
  ansible.builtin.set_fact:
    etcd_with_ssl: no
    etcd_with_ssl_options: no

- name: Reconfig
  ansible.builtin.import_tasks: config.yml

